spring:
  cloud:
    gateway:
      default-filters:
        - name: JWTAuthorizationFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: gateway

server:
  port: 8081

security:
  token:
    secret:

admitted-urls: /admission/login, /admission/registration, /fitness-data/all

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
